In [2]:
## NumPy Guide

## Introduction to NumPy Arrays
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## NumPy arrays differ from python lists in that they consist of a single datatype, and store data more efficiently.
## For example, a python integer type item actually consists of four pieces of information:

##    ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation
##    ob_type, which encodes the type of the variable
##    ob_size, which specifies the size of the following data members
##    ob_digit, which contains the actual integer value that we expect the Python variable to represent.

## As you can imagine, if you have a list of integers, you have a lot of redundancy. NumPy arrays differ in that they
## store only a single datatype, but in doing so, avoid this redundancy by specifying this extra info only once. Python
## arrays are essentially the same thing, but you can perform a variety of operations on NumPy arrays that you cannot 
## on Python arrays.

## Getting started with NumPy, import NumPy:

import numpy as np

In [18]:
## The easiest way to create a numpy array is by converting a python list:

list1 = [1, 2, 3, 4, 5]
array1 = np.array(list1)
print("array1")
print(array1)
print('\n')

## To create a multidimensional array, you can use np.array on a list of lists:

list2 = [6, 7, 8, 9, 10]
array2 = np.array([list1, list2])
print('array2')
print(array2)
print('\n')

## Various ways exist of creating a single or multidimensional array filled with arbitrary values:

# 3x5 array filled with 3.14 floats:
print("3x5 array filled with 3.14 floats")
print(np.full((3, 5), 3.14))
print('\n')

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
print("1d array filled with linear sequence, step = 2")
print(np.arange(0, 20, 2))
print('\n')

# Create a 3x3 array of random integers in the interval [0, 10)
print("3x3 array of random integers between 0 and 10")
print(np.random.randint(0, 10, (3, 3)))

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
print('\n')
print("3x3 array or normally dist. random values with mean 0 and stdev 1")
print(np.random.normal(0, 1, (3, 3)))

## Other ways exist...but I'm not going to list them all here...Google exists for that

array1
[1 2 3 4 5]


array2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


3x5 array filled with 3.14 floats
[[ 3.14  3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14  3.14]]


1d array filled with linear sequence, step = 2
[ 0  2  4  6  8 10 12 14 16 18]


3x3 array of random integers between 0 and 10
[[0 7 9]
 [9 4 9]
 [2 8 2]]


3x3 array or normally dist. random values with mean 0 and stdev 1
[[ 0.14333953  0.73794765  0.36158562]
 [-0.13241717 -0.62410284  0.79313297]
 [ 1.18300066  0.08018825 -0.19774118]]


In [26]:
## Numpy arrays can be indexed and sliced just like python lists. This applices to single and multidimensional arrays.

np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print(x1)
print('\n')
print(x2)
print('\n')
print(x3)
print('\n')

## Index numpy arrays using square brackets, just like a python list:
print("Indexing using single value:")
print('\n')
print(x1[0])
print('\n')
print(x2[0])
print('\n')
print(x3[0])


[5 0 3 3 7 9]


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


Indexing using single value:


5


[3 5 2 4]


[[8 1 5 9 8]
 [9 4 3 0 3]
 [5 0 2 3 8]
 [1 3 3 3 7]]


In [29]:
## As you can see, indexing higher dimensional array using a single value returns a row for a 2d array, and a 2d matrix
## for a 3d array. To further index these higher dimensional arrays:

print(x2[1,2]) # For single value from 2d array
print(x3[1,2]) # For single row from 3d array
print(x3[1,2,3]) # For single value from 3d array


8
[2 0 0 4 5]
4


In [ ]:
## To print a row or column (from a 2d array):

print()